#!/bin/bash
yum install nginx -y &>>${LOG_FILE}
STAT_CHECK $? "Nginx Installation"
rm -rf /usr/share/nginx/html/*
STAT_CHECK $? "Remove old HTML Pages"
cd  /tmp/frontend-main/static/ && cp -r * /usr/share/nginx/html/
STAT_CHECK $? "Copying Frontend Content"
cd  /tmp/frontend-main/static/ && cp -r * /usr/share/nginx/html/
STAT_CHECK $? "Copy Nginx Config File"
systemctl enable nginx &>>${LOG_FILE} && systemctl restart nginx &>>${LOG_FILE}
STAT_CHECK $? "Restart Nginx"



